version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    environment:
      - GIN_MODE=debug
    restart: unless-stopped